# Generated by Django 3.1.7 on 2021-03-29 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscribe',
            old_name='confition',
            new_name='condition',
        ),
    ]
