# Generated by Django 3.1.7 on 2021-04-03 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0002_rename_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_keyboard',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
