# Generated by Django 3.1.7 on 2021-04-03 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0003_user_last_keyboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_keyboard',
            field=models.IntegerField(null=True),
        ),
    ]
