# Generated by Django 3.1.7 on 2021-04-03 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0004_auto_20210403_1904'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscribe',
            old_name='user_id',
            new_name='user',
        ),
    ]
