# Generated by Django 3.1.7 on 2021-04-11 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bot', '0005_auto_20210403_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='rate_type',
            field=models.CharField(max_length=4),
        ),
    ]
